# Generated by Django 5.2.7 on 2025-11-10 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userprofile",
            old_name="phone_number",
            new_name="default_phone_number",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="address",
        ),
        migrations.AddField(
            model_name="userprofile",
            name="default_country",
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="default_county",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="default_postcode",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="default_street_address1",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="default_street_address2",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="default_town_or_city",
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
