# Generated by Django 5.2.7 on 2025-11-10 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "profiles",
            "0002_rename_phone_number_userprofile_default_phone_number_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="default_full_name",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
