# Generated by Django 5.2.7 on 2025-11-07 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("checkout", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="county",
            field=models.CharField(
                choices=[("UK", "United Kingdom")], default="UK", max_length=80
            ),
        ),
    ]
