# Generated by Django 5.2.7 on 2025-11-08 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("checkout", "0002_alter_order_county"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="country",
            field=models.CharField(
                choices=[("UK", "United Kingdom")], default="UK", max_length=40
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="county",
            field=models.CharField(max_length=80),
        ),
    ]
