# Generated by Django 5.2.5 on 2025-10-23 10:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomArtworkRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("portrait", "Portrait"),
                            ("landscape", "Landscape"),
                            ("animals", "Animals"),
                            ("still_life", "Still Life"),
                        ],
                        max_length=50,
                    ),
                ),
                ("description", models.TextField()),
                (
                    "size",
                    models.CharField(
                        choices=[
                            ("small", "Small"),
                            ("medium", "Medium"),
                            ("large", "Large"),
                            ("extra_large", "Extra Large"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "material",
                    models.CharField(
                        choices=[
                            ("acrylics", "Acrylics"),
                            ("mixed_media", "Mixed Media"),
                            ("oil_paints", "Oil Paints"),
                            ("oil_pastels", "Oil Pastels"),
                            ("pencil", "Pencil"),
                            ("watercolors", "Watercolors"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "surface",
                    models.CharField(
                        choices=[
                            ("canvas", "Canvas"),
                            ("paper", "Paper"),
                            ("board", "Board"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("under_consideration", "Under Consideration"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("delivered", "Delivered"),
                        ],
                        default="under_consideration",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
