# Generated by Django 5.2.7 on 2025-10-23 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("custom_artwork_request", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customartworkrequest",
            name="reference_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="custom_artwork_references/"
            ),
        ),
    ]
