# Generated by Django 5.2.7 on 2025-10-27 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("custom_artwork_request", "0002_customartworkrequest_reference_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customartworkrequest",
            name="material",
        ),
        migrations.AddField(
            model_name="customartworkrequest",
            name="medium",
            field=models.CharField(
                choices=[
                    ("acrylics", "Acrylics"),
                    ("artists_choice", "Artist's Choice"),
                    ("oil_paints", "Oil Paints"),
                    ("oil_pastels", "Oil Pastels"),
                    ("chalk_pastels", "Chalk Pastels"),
                    ("pencil", "Pencil"),
                    ("watercolors", "Watercolors"),
                ],
                default="artists_choice",
                max_length=20,
            ),
        ),
    ]
