# Generated by Django 5.2.7 on 2025-10-27 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "custom_artwork_request",
            "0003_remove_customartworkrequest_material_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="customartworkrequest",
            name="category",
            field=models.CharField(
                choices=[
                    ("portrait", "Portrait"),
                    ("landscape", "Landscape"),
                    ("animals", "Animals"),
                    ("still_life", "Still Life"),
                ],
                default="portrait",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="customartworkrequest",
            name="description",
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name="customartworkrequest",
            name="size",
            field=models.CharField(
                choices=[
                    ("small", "Small"),
                    ("medium", "Medium"),
                    ("large", "Large"),
                    ("extra_large", "Extra Large"),
                ],
                default="small",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="customartworkrequest",
            name="surface",
            field=models.CharField(
                choices=[("canvas", "Canvas"), ("paper", "Paper"), ("board", "Board")],
                default="canvas",
                max_length=20,
            ),
        ),
    ]
