# Generated by Django 5.2.7 on 2025-11-10 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("custom_artwork_request", "0004_alter_customartworkrequest_category_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customartworkrequest",
            name="email",
            field=models.EmailField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="customartworkrequest",
            name="name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="customartworkrequest",
            name="phone_number",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
