# Generated by Django 5.2.7 on 2025-11-08 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_alter_product_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="sold",
            field=models.BooleanField(default=False),
        ),
    ]
